module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    elite: require('./elite'),
    rgb: require('./rgb'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    mountinghole: require('./mountinghole'),
    tentingpuck: require('./tentingpuck'),
}
